# Generated by Django 4.0 on 2022-02-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='certificate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='ex_dentist',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='exp_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='friendly_staff',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='happy_patients',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='mod_equip',
            field=models.IntegerField(),
        ),
    ]
