# Generated by Django 4.0 on 2022-02-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dental', '0002_alter_about_certificate_alter_about_ex_dentist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('blog_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
